CREATE TABLE IF NOT EXISTS EntryEntries( 
    id SERIAL PRIMARY KEY NOT NULL,
    uid INTEGER NOT NULL REFERENCES Users(id),
    rid INTEGER NOT NULL REFERENCES Records(id),
    etid INTEGER REFERENCES EntryTypes(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
