CREATE TABLE IF NOT EXISTS FieldEntryLinks(
    id SERIAL PRIMARY KEY NOT NULL,
    fid INTEGER NOT NULL REFERENCES Fields(id),
    etid INTEGER NOT NULL REFERENCES EntryTypes(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
